-- Prima elimina tutti i prodotti esistenti per ricaricarli correttamente
DELETE FROM public.contact_products;
DELETE FROM public.products;

-- Inserisci tutti i prodotti dal CSV con dati corretti
INSERT INTO public.products (name, category, price, description_short, description_long, inci, key_ingredients, product_url, concerns_treated, skin_types, how_to_use, brand, step, active) VALUES

-- Detergenti
('LATTE DETERGENTE', 'Detergente', 20.50, 'Detergente viso delicato con Aloe Vera', 'Caratterizzato da una profumazione fresca e rilassante, è in grado di detergere perfettamente la pelle del viso eliminandone le impurità e rimuovendo il make-up in maniera del tutto naturale.', 'Acqua, Sodio Cocoamphoacetato, Glicerina, Lauril Glucoside...', ARRAY['Aloe Vera Bio', 'Olio di Germe di Grano Bio', 'Olio Extravergine d''Oliva Bio', 'Acido Ialuronico', 'Camomilla', 'Calendula'], 'https://almanaturalbeauty.it/prodotto/latte-detergente/', ARRAY['Rossori', 'Pigmentazione', 'Oleosità', 'Idratazione'], ARRAY['Mista'], 'Applicare mattina e sera', 'Alma Natural Beauty', '1. Detergente', true),

('MOUSSE DETERGENTE VISO', 'Detergente', 15.75, 'Mousse detergente con azione sebo regolatrice', 'Deterge in profondità da smog, polveri sottili e make up con azione sebo regolatrice e lenitiva.', 'Aqua, Sodio lauroil sarcosinato, Cocamidopropil betaina...', ARRAY['Lavanda', 'Miele', 'Vitamina E', 'Proteine del grano'], 'https://almanaturalbeauty.it/prodotto/mousse-detergente-viso/', ARRAY['Texture uniforme', 'Rossori', 'Oleosità'], ARRAY['Mista'], 'Applicare su viso umido', 'Alma Natural Beauty', '1. Detergente', true),

('BIO OLIO DETERGENTE VISO', 'Detergente', 22.00, 'Olio detergente biologico delicato', 'Detergente dalla texture morbida e sensoriale, ideato per la pulizia profonda, ma delicata di viso, occhi, collo e décolleté.', 'Olio di Olus, Etere di dicaprilile, Olio di Prunus amygdalus dulcis...', ARRAY['Olio di Mandorle Dolci', 'Vitamina E'], 'https://almanaturalbeauty.it/prodotto/bio-olio-detergente-viso/', ARRAY['Idratazione', 'Oleosità', 'Texture uniforme', 'Rossori', 'Acne'], ARRAY['Secca', 'Mista', 'Normale', 'Oleosa', 'Asfittica'], 'Massaggiare sul viso asciutto', 'Alma Natural Beauty', '1. Detergente', true),

('BIO GEL DETERGENTE VISO', 'Detergente', 17.50, 'Gel detergente biologico per tutti i tipi di pelle', 'Detergente dalla texture morbida e sensoriale, ideato per la pulizia profonda, ma delicata di viso, occhi, collo e décolleté.', 'Aqua, Cocamidopropil betaina, Sodio lauroil sarcosinato...', ARRAY['Aloe Vera', 'Olio di Oliva', 'Melograno', 'Quercia'], 'https://almanaturalbeauty.it/prodotto/bio-gel-detergente-viso/', ARRAY['Idratazione', 'Pori dilatati', 'Texture uniforme'], ARRAY['Mista', 'Normale', 'Oleosa', 'Asfittica', 'Acneica'], 'Applicare su viso umido', 'Alma Natural Beauty', '1. Detergente', true),

('DETERGENTE CORPO', 'Detergente', 18.50, 'Detergente corpo delicato', 'Detergente che unisce in modo naturale l''efficacia dei suoi ingredienti selezionati ad un delicato profumo.', 'Acqua, Cocamidopropil betaina, Sodio lauroil sarcosinato...', ARRAY['Aloe Vera', 'Olio Extra Vergine d''Oliva'], 'https://almanaturalbeauty.it/prodotto/detergente-corpo/', ARRAY['Impurità e sudore', 'Secchezza cutanea', 'Pelle sensibile o irritata'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Applicare sulla pelle umida', 'Alma Natural Beauty', '1. Detergente', true),

-- Tonico
('TONICO SPRAY', 'Tonico', 14.70, 'Tonico spray idratante e rinfrescante', 'Tonico che idrata, rinfresca ed elimina delicatamente le impurità dell''epidermide.', 'Acqua, Glicerina, Succo di foglie di Aloe barbadensis...', ARRAY['Aloe Vera', 'Pantenolo', 'Calendula', 'Camomilla', 'Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/tonico-spray/', ARRAY['Pori dilatati', 'Idratazione', 'Rossori'], ARRAY['Secca', 'Mista', 'Normale', 'Acneica'], 'Vaporizzare sul viso', 'Alma Natural Beauty', '2. Tonico', true),

-- Sieri
('ACIDO IALURONICO PURO ATTIVATORE MOLECOLARE', 'Siero', 26.50, 'Siero acido ialuronico puro', 'Morbido siero a base di acido ialuronico con basso peso molecolare: 750 Kilodalton per un''azione filler garantita.', 'Aqua, Ialuronato di sodio, Benzoato di sodio...', ARRAY['Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/acido-ialuronico-puro-attivatore-molecore/', ARRAY['Rughe', 'Acne', 'Elasticità'], ARRAY['Mista', 'Asfittica'], 'Applicare prima della crema', 'Alma Natural Beauty', '3. Siero', true),

('CONTORNO OCCHI E LABBRA', 'Contorno Occhi', 19.80, 'Contorno occhi e labbra effetto lifting', 'Nuova formula in texture Velvet Lift ricca di attivi che agiscono sulle linee d''espressione.', 'Acqua, Glicerina, Betaina, Succo di foglie di Aloe barbadensis...', ARRAY['Burro di Karitè', 'Olio di Oliva', 'Olio di Germe di Grano', 'Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/contorno-occhi-labbra/', ARRAY['Occhiaie', 'Elasticità', 'Idratazione'], ARRAY['Normale', 'Mista', 'Secca', 'Grassa', 'Sensibile'], 'Tamponare delicatamente', 'Alma Natural Beauty', '3. Siero', true),

('SIERO INTENSIVO', 'Siero', 18.50, 'Siero intensivo riparatore anti-età', 'Intensivo riparatore anti-età ad effetto immediato con azione lifting naturale.', 'Acqua, Glicerina, Succo di foglie di Aloe barbadensis...', ARRAY['Acido Ialuronico', 'Resveratrolo', 'Burro di Karitè', 'Olio di Argan'], 'https://almanaturalbeauty.it/prodotto/siero-intensivo/', ARRAY['Rughe', 'Idratazione'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Applicare prima della crema', 'Alma Natural Beauty', '3. Siero', true),

('ELISIR AL BIO MELOGRANO E COLLAGENE', 'Siero', 21.50, 'Elisir al melograno e collagene', 'Siero vellutato con melograno e collagene per un effetto anti-età.', 'Acqua, Glicerina, Copolimero di acriloildimetiltaurato...', ARRAY['Melograno', 'Collagene Idrolizzato', 'Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/elisir-al-bio-melograno-e-collagene/', ARRAY['Elasticità', 'Idratazione'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Applicare prima della crema', 'Alma Natural Beauty', '3. Siero', true),

('FLUIDO ACIDI', 'Siero', 27.50, 'Fluido esfoliante con acidi', 'Lozione liquida ad azione esfoliante progressiva che leviga ed affina la grana della pelle.', 'Acqua, Glicerina, Polisorbato 20...', ARRAY['Acido Glicolico', 'Acido Lattico', 'Acido Mandelico', 'Acido Salicilico', 'Niacinamide'], 'https://almanaturalbeauty.it/prodotto/fluido-acidi/', ARRAY['Rughe', 'Acne', 'Pori dilatati'], ARRAY['Secca', 'Grassa', 'Mista', 'Sensibile', 'Matura'], 'Applicare prima del siero', 'Alma Natural Beauty', '3. Siero', true),

('SIERO ACIDI', 'Siero', 29.00, 'Siero correttore discromie', 'Siero correttore per discromie e imperfezioni cutanee con texture lemon fresh.', 'Acqua, Glicerina, Olio di ricino idrogenato PEG-40...', ARRAY['Acido Glicolico', 'Acido Lattico', 'Acido Mandelico', 'Acido Salicilico', 'Niacinamide'], 'https://almanaturalbeauty.it/prodotto/siero-acidi/', ARRAY['Viso spento', 'Rughe', 'Pori dilatati', 'Macchie e discromie', 'Eccesso di sebo'], ARRAY['Secca', 'Normale', 'Grassa', 'Sensibile', 'Mista'], 'Applicare sulle discromie', 'Alma Natural Beauty', '3. Siero', true),

-- Creme Viso
('ESFOLIANTE VISO DELICATO', 'Crema Viso', 21.50, 'Esfoliante delicato per tutti i tipi di pelle', 'Emulsione esfoliante delicata con azione schiarente su pelli con iperpigmentazioni.', 'Acqua, Trigliceride caprilico/caprico...', ARRAY['Nocciolo di Albicocca', 'Burro di Karitè', 'Olio di Mandorle Dolci'], 'https://almanaturalbeauty.it/prodotto/esfoliante-viso-delicato/', ARRAY['Rossori', 'Oleosità', 'Pori dilatati'], ARRAY['Secca', 'Oleosa', 'Mista', 'Grassa', 'Acneica'], 'Massaggiare delicatamente', 'Alma Natural Beauty', '4. Crema', true),

('CREMA GIORNO NO-AGE', 'Crema Viso', 29.50, 'Crema giorno anti-età', 'Mix di estratti naturali e biologici con effetto lifting naturale.', 'Acqua, Trigliceride caprilico/caprico...', ARRAY['Burro di Karitè', 'Aloe Vera', 'Olio di Mandorle Dolci', 'Resveratrolo', 'Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/crema-giorno-no-age/', ARRAY['Idratazione', 'Elasticità'], ARRAY['Normale', 'Secca', 'Mista', 'Sensibile'], 'Applicare al mattino', 'Alma Natural Beauty', '4. Crema', true),

('CREMA NOTTE NO-AGE', 'Crema Viso', 29.50, 'Crema notte rigenerante', 'Crema notturna per combattere l''invecchiamento cutaneo durante il riposo.', 'Acqua, Trigliceride caprilico/caprico...', ARRAY['Burro di Karitè', 'Olio di Mandorle Dolci', 'Calendula', 'Resveratrolo', 'Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/crema-notte-no-age/', ARRAY['Elasticità', 'Idratazione', 'Rughe'], ARRAY['Secca', 'Normale', 'Grassa', 'Mista', 'Sensibile'], 'Applicare la sera', 'Alma Natural Beauty', '4. Crema', true),

('CREMA VISO GIORNO ROSA CANINA E MOSQUETA', 'Crema Viso', 20.80, 'Crema giorno con rosa canina', 'Trattamento restitutivo con rosa canina e rosa Mosqueta per idratazione profonda.', 'Acqua, Palmitato di etilesile...', ARRAY['Rosa Canina', 'Rosa Mosqueta', 'Collagene Idrolizzato'], 'https://almanaturalbeauty.it/prodotto/crema-viso-giorno-rosa-canina-e-mosqueta/', ARRAY['Idratazione', 'Rossori', 'Pori dilatati', 'Invecchiamento', 'Viso spento'], ARRAY['Normale', 'Secca', 'Mista', 'Grassa', 'Sensibile'], 'Applicare al mattino', 'Alma Natural Beauty', '4. Crema', true),

('CREMA VISO NOTTE FIORDALISO', 'Crema Viso', 20.50, 'Crema notte al fiordaliso', 'Trattamento rigenerante notturno con acqua di Fiordaliso.', 'Acqua, Palmitato di etilesile...', ARRAY['Acqua di Fiordaliso', 'Olio di Mandorle Dolci', 'Malva', 'Menta'], 'https://almanaturalbeauty.it/prodotto/crema-viso-notte-fiordaliso/', ARRAY['Idratazione', 'Rossori', 'Invecchiamento', 'Perdita di tono', 'Stanchezza e stress cutaneo'], ARRAY['Secca', 'Normale', 'Grassa', 'Sensibile', 'Mista'], 'Applicare la sera', 'Alma Natural Beauty', '4. Crema', true),

('CREMA ACIDI H24', 'Crema Viso', 29.50, 'Crema viso acidi H24', 'Crema dalla texture corposa per pelli mature, discromiche e acneiche.', 'Acqua, Trigliceride caprilico/caprico...', ARRAY['Acido Glicolico', 'Acido Mandelico', 'Acido Salicilico', 'Niacinamide'], 'https://almanaturalbeauty.it/prodotto/crema-acidi-h24/', ARRAY['Rughe', 'Viso spento', 'Macchie e discromie', 'Idratazione'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Applicare mattina e sera', 'Alma Natural Beauty', '4. Crema', true),

-- Creme Corpo
('ESFOLIANTE CORPO', 'Crema Corpo', 24.60, 'Esfoliante corpo con microsfere', 'Esfoliante corpo con microsfere di nocciolo di albicocca.', 'Acqua, Trigliceride caprilico/caprico...', ARRAY['Microsfere di Albicocca', 'Aloe Vera Bio', 'Olio di Oliva', 'Burro di Karitè'], 'https://almanaturalbeauty.it/prodotto/esfoliante-corpo/', ARRAY['Cellule morte', 'Pelle secca', 'Pelle ruvida'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Massaggiare su pelle umida', 'Alma Natural Beauty', '4. Crema', true),

('CREMA CORPO NO-AGE', 'Crema Corpo', 23.50, 'Crema corpo anti-età', 'Dona benessere e freschezza con una fragranza naturale neutra.', 'Acqua, Trigliceride caprilico/caprico...', ARRAY['Burro di Karitè', 'Aloe Vera', 'Olio di Macadamia', 'Acido Ialuronico'], 'https://almanaturalbeauty.it/prodotto/crema-corpo-no-age/', ARRAY['Pelle secca', 'Elasticità', 'Viso spento'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Applicare dopo il bagno', 'Alma Natural Beauty', '4. Crema', true),

('CREMA LIPO CELL CAFFÈ VERDE', 'Crema Corpo', 29.90, 'Crema anticellulite caffè verde', 'Crema anticellulite con cacao e caffè verde.', 'Acqua, esteri di tribehenin PEG-20...', ARRAY['Cacao', 'Caffè Verde', 'Guaranà'], 'https://almanaturalbeauty.it/prodotto/crema-lipo-cell-caffe-verde/', ARRAY['Ritenzione idrica e gonfiore', 'Pelle poco tonica o rilassata', 'Cellulite', 'Adiposità localizzate'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Massaggiare con movimenti circolari', 'Alma Natural Beauty', '4. Crema', true),

-- Maschere
('MASCHERA GLOBALE', 'Maschera', 18.50, 'Maschera viso globale', 'Emulsione naturale innovativa con effetto lifting naturale.', 'Acqua, glicerina, trigliceride caprilico/caprico...', ARRAY['Aloe Vera', 'Acido Ialuronico', 'Olio di Oliva', 'Collagene Idrolizzato'], 'https://almanaturalbeauty.it/prodotto/maschera-gllobale/', ARRAY['Idratazione', 'Rughe', 'Pori dilatati'], ARRAY['Secca', 'Normale', 'Mista'], 'Applicare e lasciare in posa', 'Alma Natural Beauty', '5. Maschera', true),

('PEELING VISO/CORPO PERLE DI JOJOBA', 'Maschera', 14.70, 'Peeling con perle di jojoba', 'Rinnovamento cutaneo con perle di Jojoba.', 'Acqua, Glicerina, Sorbitolo...', ARRAY['Perle di Jojoba', 'Proteine del Grano', 'Olio di Lavanda'], 'https://almanaturalbeauty.it/prodotto/peeling-viso-corpo-perle-di-jojoba/', ARRAY['Pori dilatati', 'Idratazione'], ARRAY['Secca', 'Grassa', 'Mista', 'Acneica', 'Normale'], 'Massaggiare delicatamente', 'Alma Natural Beauty', '4. Crema', true),

-- Oli
('OLIO PURO', 'Olio', 20.70, 'Olio puro 100% naturale', 'Olio delicato con azione idratante ed emolliente.', 'Olio di Olus, Etere dicaprilico...', ARRAY['Olio di Mandorle Dolci', 'Olio di Girasole', 'Vitamina E'], 'https://almanaturalbeauty.it/prodotto/olio-puro/', ARRAY['Pelle secca', 'Rossori', 'Invecchiamento', 'Idratazione'], ARRAY['Normale', 'Secca', 'Grassa', 'Mista', 'Sensibile'], 'Massaggiare sulla pelle', 'Alma Natural Beauty', '7. Olio', true),

-- Altri prodotti
('BURRO PERFECT LIPS', 'Burro Labbra', 7.00, 'Burro labbra emolliente', 'Burro profumato ottimo come emolliente delicato e naturale.', 'Burro di Butyrospermum parkii...', ARRAY['Burro di Karitè', 'Olio di Girasole', 'Vitamina E'], 'https://almanaturalbeauty.it/prodotto/burro-perfect-lips/', ARRAY['Idratazione', 'Elasticità'], ARRAY['Tutte'], 'Applicare sulle labbra', 'Alma Natural Beauty', '4. Crema', true);
